# config.yaml
titulo: Editor de imagenes
descripcion: Agrega efectos a tus imagenes
conversionimg:
  nivelConversion: 5
  version: 1.0
  efectos:
    - nombre: "Escala de grises"
      descripcion: "Convierte la imagen a escala de grises"
      tipo: "filtro"
      parametros:
        - nombre: "intensidad"
          tipo: "entero"
          valorPorDefecto: 50
          rango: [0, 100]
    - nombre:
 
